---
- name: Check Windows OS version
  hosts: all
  connection: local
  gather_facts: true
  tasks:
    - name: Importing role for checking OS version
      import_role:
        name: checking_os_version
