---
- name: Sending mail to requester
  hosts: "device_name"
  ignore_unreachable: yes
  gather_facts: no
  tasks:
    - name: writting an email
      mail: 
        host: grzxsmtp.andritz.com
        port: 25
        to: "{{ to_address }}"
        subject: ""
        body: "Please find the attached file "
        secure: starttls
        from: ""
        attach:
          - "{{ email_file }}"
